db:
  host: localhost
  port: 5432
  name: file_storage
  user: postgres
  pass: password

server:
  port: 8091
  tomcat.max-http-post-size: 62914560

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.pass}
  ## Flyway
  flyway:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    user: ${db.user}
    password: ${db.pass}
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    ## Hibernate Properties
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  ## MULTIPART (MultipartProperties)
  servlet.multipart:
    enabled: true
    file-size-threshold: 2KB
    max-file-size: 2000MB
    max-request-size: 2150MB
## Hibernate Logging
logging.level:
  org.hibernate.SQL: DEBUG
  org.jooq: DEBUG

## File Storage Properties
storage:
  upload-dir: ./uploads
#  upload-url: http://localhost:8091/file-server/uploadFile
## hashids properties
hashids:
  salt: "dWG8TNmWjYz8WP6DSpUgeCmFbp9SP6XjdyPg4q4BnZaEavQfC5ghdag8FkF3t9sL"
  min-length: 64
  alphabet: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz

