const FileResourceType = Object.freeze({
  PAYER_PASSPORT_FRONT: "PAYER_PASSPORT_FRONT",
  PAYER_PASSPORT_BACK: "PAYER_PASSPORT_BACK",
  PAYER_SALARY_REPORT: "PAYER_SALARY_REPORT",
  GUARANTOR_PASSPORT_FRONT: "GUARANTOR_PASSPORT_FRONT",
  GUARANTOR_PASSPORT_BACK: "GUARANTOR_PASSPORT_BACK",
  GUARANTOR_SALARY_REPORT: "GUARANTOR_SALARY_REPORT"
});

export default FileResourceType;
