keycloak.configurationFile: classpath:keycloak.json

db:
  host: localhost
  port: 5432
  name: postgres
  user: postgres
  pass: password

server.port: 8095

spring:
  main.allow-bean-definition-overriding: true
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false
  jpa.open-in-view: false
  jpa.show-sql: false
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
  #  #Flyway
  flyway:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    user: ${db.user}
    password: ${db.pass}
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
  #Datasource
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.pass}
# Logger
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.jooq.tools.LoggerListener: DEBUG
#Hashids
hashids:
  salt: "eYKM+jt6N!^LZ#au*?Eav$@YJdhSx=kt"
  minLength: 4
  alphabet: abcdef0123456789