-- insert regions
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '17', 'O`ZBEKISTON RESPUBLIKASI', 'РЕСПУБЛИКА УЗБЕКИСТАН', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703', 'ANDIJON VILOYATI', 'АНДИЖАНСКАЯ ОБЛАСТЬ', 'Andijon sh.', 'г. Андижан');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703202', 'OLTINKO`L TUMANI', 'АЛТЫНКУЛЬСКИЙ РАЙОН', 'Oltinko`l a.p.', 'нп Алтынкуль');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703203', 'ANDIJON TUMANI', 'АНДИЖАНСКИЙ РАЙОН', 'Kuyganyor shaharchasi', 'гп Куйган - яр');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703206', 'BALIQCHI TUMANI', 'БАЛЫКЧИНСКИЙ РАЙОН', 'Baliqchi shaharchasi', 'гп Баликчи');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703209', 'BO`Z TUMANI', 'БОЗСКИЙ РАЙОН', 'Bo`z shaharchasi', 'гп Боз');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703210', 'BULOQBOSHI TUMANI', 'БУЛАКБАШИНСКИЙ РАЙОН', 'Buloqboshi shaharchasi', 'гп Булокбоши');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703211', 'JALAQUDUQ TUMANI', 'ЖАЛАКУДУКСКИЙ РАЙОН', 'Jalaquduq sh.', 'г. Жалакудук');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703214', 'IZBOSKAN TUMANI', 'ИЗБАСКАНСКИЙ РАЙОН', 'Paytug sh.', 'г. Пайтуг');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703217', 'ULUG`NOR TUMANI', 'УЛУГНОPСКИЙ РАЙОН', 'Oq oltin shaharchasi', 'гп Ок-олтин');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703220', 'QO`RG`ONTEPA TUMANI', 'КУРГАНТЕПИНСКИЙ РАЙОН', 'Qo`rg`ontepa sh.', 'г. Кургантепа');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703224', 'ASAKA TUMANI', 'АСАКИНСКИЙ РАЙОН', 'Asaka sh.', 'г. Асака');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703227', 'MARXAMAT TUMANI', 'МАРХАМАТСКИЙ РАЙОН', 'Marxamat sh.', 'г. Мархамат');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703230', 'SHAXRIXON TUMANI', 'ШАХРИХАНСКИЙ РАЙОН', 'Shaxrixon sh.', 'г. Шахрихан');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703232', 'PAXTAOBOD TUMANI', 'ПАХТААБАДСКИЙ РАЙОН', 'Paxtaobod sh.', 'г. Пахтаабад');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703236', 'XO`JAOBOD TUMANI', 'ХОДЖААБАДСКИЙ РАЙОН', 'Xo`jaobod sh.', 'г. Ходжаабад');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703401', 'Andijon shahri', 'Город Андижан', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1703408', 'Xonobod shahri', 'Город Ханабад', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1706', 'BUXORO VILOYATI', 'БУХАРСКАЯ ОБЛАСТЬ', 'Buxoro sh.', 'г. Бухара');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1706204', 'Olot tumani', 'Алатский район', 'Olot sh.', 'г. Алат');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1706207', 'BUXORO TUMANI', 'БУХАРСКИЙ РАЙОН', 'Gala Osiyo shaharchasi', 'г. Галлаасия');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1706212', 'VOBKENT TUMANI', 'ВАБКЕНТСКИЙ РАЙОН', 'Vobkent sh.', 'г. Вабкент');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1706215', 'G`IJDUVON TUMANI', 'ГИЖДУВАНСКИЙ РАЙОН', 'G`ijduvon sh.', 'г. Гиждуван');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1706219', 'KOGON TUMANI', 'КАГАНСКИЙ РАЙОН', 'Kogon sh.', 'г. Каган');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1706230', 'QORAKO`L TUMANI', 'КАРАКУЛЬСКИЙ РАЙОН', 'Qorako`l sh.', 'г. Каракуль');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1706232', 'QOROVULBOZOR TUMANI', 'КАРАУЛБАЗАРСКИЙ РАЙОН', 'Qorovulbozor sh.', 'г. Каpаулбазаp');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1706240', 'PESHKU TUMANI', 'ПЕШКУНСКИЙ РАЙОН', 'Yangibozor shaharchasi', 'гп Янгибозор');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1706242', 'ROMITAN TUMANI', 'РОМИТАНСКИЙ РАЙОН', 'Romitan sh.', 'г. Ромитан');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1706246', 'JONDOR TUMANI', 'ЖОНДОPСКИЙ РАЙОН', 'Jondor shaharchasi', 'гп Жондор');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1706258', 'SHOFIRKON TUMANI', 'ШАФИРКАНСКИЙ РАЙОН', 'Shofirkon sh.', 'г. Шафиркан');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1706401', 'Buxoro shahri', 'Город Бухара', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ( '1706403', 'Kogon shahri', 'Город Каган', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1708','JIZZAX VILOYATI','Jizzax sh.','ДЖИЗАКСКАЯ ОБЛАСТЬ','г. Джизак');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1708201','ARNASOY TUMANI','G`oliblar shaharchasi','АРНАСАЙСКИЙ РАЙОН','гп Голиблаp');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1708204','BAXMAL TUMANI','O`smat shaharchasi','БАХМАЛЬСКИЙ РАЙОН','гп Усмат');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1708209','G`ALLAOROL TUMANI','G`allaorol sh.','ГАЛЛЯАРАЛЬСКИЙ РАЙОН','г. Галляарал');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1708212','SHAROF RASHIDOV TUMANI','Uchtepa shaharchasi','ШАРОФ РАШИДОВСКИЙ РАЙОН','гп Уч-тепа');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1708215','DO`STLIK TUMANI','Do`stlik sh.','ДУСТЛИКСКИЙ РАЙОН','г. Дустлик');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1708218','ZOMIN TUMANI','Zomin shaharchasi','ЗААМИНСКИЙ РАЙОН','гп Заамин');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1708220','ZARBDOR TUMANI','Zarbdor shaharchasi','ЗАРБДАРСКИЙ РАЙОН','гп Зарбдар');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1708223','MIRZACHO`L TUMANI','Gagarin sh.','МИРЗАЧУЛЬСКИЙ РАЙОН','г. Гагарин');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1708225','ZAFAROBOD TUMANI','Zafarobod shaharchasi','ЗАФАРАБАДСКИЙ РАЙОН','гп Зафарабад');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1708228','PAXTAKOR TUMANI','Paxtakor sh.','ПАХТАКОРСКИЙ РАЙОН','г. Пахтакор');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1708235','FORISH TUMANI','Bog`don shaharchasi','ФАРИШСКИЙ РАЙОН','гп Богдон');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1708237','YANGIOBOD TUMANI','Balandchaqir a.p.','ЯНГИАБАДСКИЙ РАЙОН','нп Баландчакир');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1708401','Jizzax shahri','Город Джизак', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710','QASHQADARYO VILOYATI','Qarshi sh.','КАШКАДАРЬИНСКАЯ ОБЛАСТЬ','г. Карши');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710207','G`UZOR TUMANI','G`uzor sh.','ГУЗАРСКИЙ РАЙОН','г. Гузар');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710212','DEHQONOBOD TUMANI','Karashina shaharchasi','ДЕХКАНАБАДСКИЙ РАЙОН','гп Корашина');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710220','QAMASHI TUMANI','Qamashi sh.','КАМАШИНСКИЙ РАЙОН','г. Камаши');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710224','QARSHI TUMANI','Beshkent sh.','КАРШИНСКИЙ РАЙОН','г. Бешкент');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710229','KOSON TUMANI','Koson sh.','КАСАНСКИЙ РАЙОН','г. Касан');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710232','KITOB TUMANI','Kitob sh.','КИТАБСКИЙ РАЙОН','г. Китаб');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710233','MIRISHKOR TUMANI','Yangi Mirishkor shaharchasi','МИРИШКОРСКИЙ РАЙОН','гп Янги Миришкор');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710234','MUBORAK TUMANI','Muborak sh.','МУБАРЕКСКИЙ РАЙОН','г. Мубарек');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710235','NISHON TUMANI','Yangi Nishon sh.','НИШАНСКИЙ РАЙОН','г. Янги-Нишан');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710237','KASBI TUMANI','Mug`lon shaharchasi','КАСБИНСКИЙ РАЙОН','гп Муглон');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710242','CHIROQCHI TUMANI','Chiroqchi sh.','ЧИРАКЧИНСКИЙ РАЙОН','г. Чиракчи');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710245','SHAHRISABZ TUMANI','Shahrisabz sh.','ШАХРИСАБЗСКИЙ РАЙОН','г. Шахрисабз');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710250','YAKKABOG` TUMANI','Yakkabog` sh.','ЯККАБАГСКИЙ РАЙОН','г. Яккабаг');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710401','Qarshi','Карши', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1710405','Shahrisabz','Шахрисабз', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1712','NAVOIY VILOYATI','Navoiy sh.','НАВОИЙСКАЯ ОБЛАСТЬ','г. Навои');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1712211','Konimex tumani','Konimex shaharchasi','Канимехский район','гп Канимех');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1712216','QIZILTEPA TUMANI','Qiziltepa sh.','КЫЗЫЛТЕПИНСКИЙ РАЙОН','г. Кызылтепа');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1712230','NAVBAHOR TUMANI','Beshrabot a.p.','НАВБАХОРСКИЙ РАЙОН','нп Бешрабад');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1712234','KARMANA TUMANI','Karmana shaharchasi','КАРМАНИНСКИЙ РАЙОН','гп Кармана');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1712238','NUROTA TUMANI','Nurota sh.','НУРАТИНСКИЙ РАЙОН','г. Нурата');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1712244','TOMDI TUMANI','Tomdibuloq shaharchasi','ТАМДЫНСКИЙ РАЙОН','гп Томдибулок');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1712248','UCHQUDUQ TUMANI','Uchquduq sh.','УЧКУДУКСКИЙ РАЙОН','г. Учкудук');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1712251','XATIRCHI TUMANI','Yangirabod sh.','ХАТЫРЧИНСКИЙ РАЙОН','г. Янгирабод');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1712401','Navoiy shahri','Город Навои', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1712408','Zarafshon','Заpафшан', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1714','NAMANGAN VILOYATI','Namangan sh.','НАМАНГАНСКАЯ ОБЛАСТЬ','г. Наманган');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1714204','MINGBULOQ TUMANI','Jo`masho`y shaharchasi','МИНГБУЛАКСКИЙ PАЙОН','гп Джумашуй');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1714207','KOSONSOY TUMANI','Kosonsoy sh.','КАСАНСАЙСКИЙ РАЙОН','г. Касансай');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1714212','NAMANGAN TUMANI','Toshbuloq shaharchasi','НАМАНГАНСКИЙ РАЙОН','гп Ташбулак');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1714216','NORIN TUMANI','Xaqqulobod sh.','НАРЫНСКИЙ РАЙОН','г. Хаккулабад');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1714219','POP TUMANI','Pop sh.','ПАПСКИЙ РАЙОН','г. Пап');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1714224','TO`RAQO`RG`ON TUMANI','To`raqo`rg`on sh.','ТУРАКУРГАНСКИЙ РАЙОН','г. Туракурган');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1714229','UYCHI TUMANI','Uychi shaharchasi','УЙЧИНСКИЙ РАЙОН','гп Уйчи');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1714234','UCHQO`RG`ON TUMANI','Uchqo`rg`on sh.','УЧКУРГАНСКИЙ РАЙОН','г. Учкурган');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1714236','CHORTOQ TUMANI','Chortoq sh.','ЧАРТАКСКИЙ РАЙОН','г. Чартак');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1714237','CHUST TUMANI','Chust sh.','ЧУСТСКИЙ РАЙОН','г. Чуст');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1714242','YANGIQO`RG`ON TUMANI','Yangiqo`rg`on shaharchasi','ЯНГИКУРГАНСКИЙ РАЙОН','гп Янгикурган');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1714401','Namangan shahri','Город Наманган', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718','SAMARQAND VILOYATI','Samarqand sh.','САМАРКАНДСКАЯ ОБЛАСТЬ','г. Самарканд');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718203','Oqdaryo tumani','Loyish shaharchasi','Акдарьинский район','гп Лаиш');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718206','BULUNG`UR TUMANI','Bulung`ur sh.','БУЛУНГУРСКИЙ РАЙОН','г. Булунгур');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718209','JOMBOY TUMANI','Jomboy sh.','ДЖАМБАЙСКИЙ РАЙОН','г. Джамбай');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718212','ISHTIXON TUMANI','Ishtixon sh.','ИШТЫХАНСКИЙ РАЙОН','г. Иштыхан');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718215','KATTAQO`RG`ON TUMANI','Payshanba shaharchasi','КАТТАКУРГАНСКИЙ РАЙОН','гп Пайшанба');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718216','QO`SHRABOT TUMANI','Qo`shrabot shaharchasi','КОШРАБАДСКИЙ РАЙОН','гп Кушрабад');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718218','NARPAY TUMANI','Oqtosh sh.','НАРПАЙСКИЙ РАЙОН','г. Акташ');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718224','PAYARIQ TUMANI','Payariq sh.','ПАЙАРЫКСКИЙ РАЙОН','г.Пайаpык');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718227','PASTDARG`OM TUMANI','Juma sh.','ПАСТДАРГОМСКИЙ РАЙОН','г. Джума');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718230','PAXTACHI TUMANI','Ziyovuddin shaharchasi','ПАХТАЧИЙСКИЙ РАЙОН','гп Зиатдин');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718233','SAMARQAND TUMANI','Gulobod shaharchasi','САМАРКАНДСКИЙ РАЙОН','гп Гулабад');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718235','NUROBOD TUMANI','Nurobod sh.','НУРАБАДСКИЙ РАЙОН','г. Нурабад');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718236','URGUT TUMANI','Urgut sh.','УРГУТСКИЙ РАЙОН','г. Ургут');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718238','TAYLOQ TUMANI','Toyloq shaharchasi','ТАЙЛЯКСКИЙ РАЙОН','гп Тайлок');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718401','Samarqand shahri','Город Самарканд', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1718406','Kattaqo`rg`on shahri','Город Каттакурган', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1722','SURXANDARYO VILOYATI','Termiz sh.','СУРХАНДАРЬИНСКАЯ ОБЛАСТЬ','г. Термез');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1722201','OLTINSOY TUMANI','Qorliq shaharchasi','АЛТЫНСАЙСКИЙ РАЙОН','гп Корлик');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1722202','ANGOR TUMANI','Angor shaharchasi','АНГОРСКИЙ РАЙОН','гп Ангор');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1722204','BOYSUN TUMANI','Boysun sh.','БАЙСУНСКИЙ РАЙОН','г. Байсун');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1722207','MUZRABOT TUMANI','Xalqobod shaharchasi','МУЗРАБАДСКИЙ РАЙОН','гп Халкабад');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1722210','DENOV TUMANI','Denov sh.','ДЕНАУСКИЙ РАЙОН','г. Денау');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1722212','JARQO`RG`ON TUMANI','Jarqo`rg`on sh.','ДЖАРКУРГАНСКИЙ РАЙОН','г. Джаркурган');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1722214','QUMQO`RG`ON TUMANI','Qumqo`rg`on sh.','КУМКУРГАНСКИЙ РАЙОН','г. Кумкурган');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1722215','QIZIRIQ TUMANI','Sariq shaharchasi','КИЗИРИКСКИЙ РАЙОН','гп Сарик');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1722217','SARIOSIYO TUMANI','Sariosiyo shaharchasi','САРИАСИЙСКИЙ РАЙОН','гп Сариасия');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1722220','TERMIZ TUMANI','Uchqizil shaharchasi','ТЕРМЕЗСКИЙ РАЙОН','гп Учкизил');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1722221','UZUN TUMANI','Uzun shaharchasi','УЗУНСКИЙ РАЙОН','гп Узун');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1722223','SHEROBOD TUMANI','Sherobod sh.','ШЕРАБАДСКИЙ РАЙОН','г. Шерабад');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1722226','SHO`RCHI TUMANI','Sho`rchi sh.','ШУРЧИНСКИЙ РАЙОН','г. Шурчи');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1722401','Termiz shahri','Город Термез', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1724','SIRDARYO VILOYATI','Guliston sh.','СЫРДАРЬИНСКАЯ ОБЛАСТЬ','г. Гулистан');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1724206','OQOLTIN TUMANI','Sardoba shaharchasi','АКАЛТЫНСКИЙ РАЙОН','гп Сардоба');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1724212','BOYOVUT TUMANI','Boyovut shaharchasi','БАЯУТСКИЙ РАЙОН','гп Баяут');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1724216','SAYXUNOBOD TUMANI','Sayxun shaharcha','САЙХУНАБАДСКИЙ РАЙОН','гп Сайхун');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1724220','GULISTON TUMANI','Dehqonobod shaharchasi','ГУЛИСТАНСКИЙ РАЙОН','гп Дехканабад');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1724226','SARDOBA TUMANI','Paxtaobod shaharchasi','САРДОБСКИЙ РАЙОН','гп Пахтаабад');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1724228','MIRZAOBOD TUMANI','Navro`z shaharchasi','МИРЗААБАДСКИЙ РАЙОН','гп Навруз');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1724231','SIRDARYO TUMANI','Sirdaryo sh.','СЫРДАРЬИНСКИЙ РАЙОН','г. Сырдарья');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1724235','XOVOS TUMANI','Xovos shaharchasi','ХАВАССКИЙ РАЙОН','гп Хавас');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1724401','Guliston shahri','Город Гулистан', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1724410','Shirin shahri','Город Шиpин', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1724413','Yangiyer shahri','Город Янгиеp', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1726','TOSHKENT SHAHRI','ГОРОД ТАШКЕНТ', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1726262','Uchtepa tumani','Учтепинский район', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1726264','Bektemir tumani','Бектемирский район', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1726266','Yunusobod tumani','Юнусабадский район', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1726269','Mirzo Ulug`bek tumani','Мирзо-Улугбекский район', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1726273','Mirobod tumani','Мирабадский район', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1726277','Shayxontoxur tumani','Шайхантахурский район', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1726280','Olmazor tumani','Алмазарский район', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1726283','Sirg`ali tumani','Сергелийский район', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1726287','Yakkasaroy tumani','Яккасарайский район', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1726290','Yashnobod tumani','Яшнободский район', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1726294','Chilonzor tumani','Чиланзарский район', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727','TOSHKENT VILOYATI','Toshkent sh.','ТАШКЕНТСКАЯ ОБЛАСТЬ','г. Ташкент');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727206','OQQO`RG`ON TUMANI','Oqqo`rg`on sh.','АККУРГАНСКИЙ РАЙОН','г. Аккурган');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727212','OHANGARON TUMANI','Ohangaron sh.','АХАНГАРАНСКИЙ РАЙОН','г. Ахангаран');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727220','BEKOBOD TUMANI','Zafar shaharchasi','БЕКАБАДСКИЙ РАЙОН','гп Зафар');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727224','BO`STONLIQ TUMANI','G`azalkent sh.','БОСТАНЛЫКСКИЙ РАЙОН','г. Газалкент');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727228','BO`KA TUMANI','Bo`ka sh.','БУКИНСКИЙ РАЙОН','г. Бука');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727233','QIYICHIRCHIQ TUMANI','Do`stobod sh.','КУЙИЧИРЧИКСКИЙ РАЙОН','г. Дустобод');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727237','ZANGIOTA TUMANI','Eshonguzar shaharchasi','ЗАНГИАТИНСКИЙ РАЙОН','гп Эшангузар');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727239','YUQORICHIRCHIQ TUMANI','Yangibozor shaharchasi','ЮКОРИЧИРЧИКСКИЙ РАЙОН','гп Янгибазар');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727248','QIBRAY TUMANI','Qibray shaharchasi','КИБРАЙСКИЙ РАЙОН','гп Кибрай');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727249','PARKENT TUMANI','Parkent sh.','ПАРКЕНТСКИЙ РАЙОН','г. Паркент');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727250','PSKENT TUMANI','Pskent sh.','ПСКЕНТСКИЙ РАЙОН','г. Пскент');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727253','O`RTACHIRCHIQ TUMANI','To`ytepa sh.','УРТАЧИРЧИКСКИЙ РАЙОН','г. Тойтепа');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727256','CHINOZ TUMANI','Chinoz sh.','ЧИНАЗСКИЙ РАЙОН','г. Чиназ');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727259','YANGIYO`L TUMANI','Yangiyo`l sh.','ЯНГИЮЛЬСКИЙ РАЙОН','г.Янгиюль');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727265','TOSHKENT TUMANI','Keles sh.','ТАШКЕНТСКИЙ РАЙОН','г.Келес');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727404','Olmaliq shahri','Город Алмалык', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727407','Angren shahri','Город Ангрен', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727413','Bekobod shahri','Город Бекабад', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1727419','Chirchiq shahri','Город Чиpчик', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730','FARG`ONA VILOYATI','Farg`ona sh.','ФЕРГАНСКАЯ ОБЛАСТЬ','г. Фергана');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730203','OLTIARIQ TUMANI','Oltiariq shaharchasi','АЛТЫАРЫКСКИЙ РАЙОН','гп Алтыарык');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730206','QO`SHTEPA TUMANI','Langar a.p.','КУШТЕПИНСКИЙ РАЙОН','нп Лангар');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730209','BOG`DOD TUMANI','Bog`dod shaharchasi','БАГДАДСКИЙ РАЙОН','гп Багдад');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730212','BUVAYDA TUMANI','Ibrat shaharchasi','БУВАЙДИНСКИЙ РАЙОН','гп Ибрат');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730215','BESHARIQ TUMANI','Beshariq sh.','БЕШАРЫКСКИЙ РАЙОН','г. Бешарык');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730218','QUVA TUMANI','Quva sh.','КУВИНСКИЙ РАЙОН','г. Кува');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730221','UCHKO`PRIK TUMANI','Uchko`prik shaharchasi','УЧКУПРИКСКИЙ РАЙОН','гп Учкуприк');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730224','RISHTON TUMANI','Rishton sh.','РИШТАНСКИЙ РАЙОН','г. Риштан');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730226','SO`X TUMANI','Ravon shaharchasi','СОХСКИЙ РАЙОН','гп Равон');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730227','TOSHLOQ TUMANI','Toshloq shaharchasi','ТАШЛАКСКИЙ РАЙОН','гп Ташлак');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730230','O`ZBEKISTON TUMANI','Yaypan sh.','УЗБЕКИСТАНСКИЙ РАЙОН','г. Яйпан');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730233','FARG`ONA TUMANI','Chimyon shaharchasi','ФЕРГАНСКИЙ РАЙОН','гп Чимен');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730236','DANG`ARA TUMANI','Dang`ara shaharchasi','ДАНГАРИНСКИЙ РАЙОН','гп Дангара');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730238','FURQAT TUMANI','Navbahor shaharchasi','ФУРКАТСКИЙ РАЙОН','гп Навбахор');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730242','YOZYOVON TUMANI','Yozyovon shaharchasi','ЯЗЪЯВАНСКИЙ РАЙОН','гп Язъяван');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730401','Farg`ona shahri','Город Фергана', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730405','Qo`qon shahri','Город Коканд', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730408','Quvasoy shahri','Город Кувасай', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1730412','Marg`ilon shahri','Город Маpгилан', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1733','XORAZM VILOYATI','Urganch sh.','ХОРЕЗМСКАЯ ОБЛАСТЬ','г. Ургенч');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1733204','BOG`OT TUMANI','Bog`ot shaharchasi','БАГАТСКИЙ РАЙОН','гп Багат');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1733208','GURLAN TUMANI','Gurlan shaharchasi','ГУРЛЕНСКИЙ РАЙОН','гп Гурлен');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1733212','QO`SHKO`PIR TUMANI','Qo`shko`pir shaharchasi','КОШКУПЫРСКИЙ РАЙОН','гп Кошкупыр');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1733217','URGANCH TUMANI','Qoroul a.p.','УРГЕНЧСКИЙ РАЙОН','нп Караул');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1733220','XAZORASP TUMANI','Xazorasp shaharchasi','ХАЗАРАСПСКИЙ РАЙОН','гп Хазарасп');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1733223','XONQA TUMANI','Xonqa shaharchasi','ХАНКИНСКИЙ РАЙОН','гп Ханка');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1733226','XIVA TUMANI','Xiva sh.','ХИВИНСКИЙ РАЙОН','г. Хива');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1733230','SHOVOT TUMANI','Shovot shaharchasi','ШАВАТСКИЙ РАЙОН','гп Шават');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1733233','YANGIARIQ TUMANI','Yangiariq shaharchasi','ЯНГИАРЫКСКИЙ РАЙОН','гп Янгиарык');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1733236','YANGIBOZOR TUMANI','Yangibozor shaharchasi','ЯНГИБАЗАРСКИЙ РАЙОН','гп Янгибазар');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1733401','Urganch shahri','Город Ургенч', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1733406','Xiva shahri','Город Хива', null, null);
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735','Qoraqalpog`iston Respublikasi','Nukus sh.','Республика Каракалпакстан','г. Hукус');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735204','AMUDARYO TUMANI','Mang`it sh.','АМУДАРЬИНСКИЙ РАЙОН','г. Мангит');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735207','BERUNIY TUMANI','Beruniy sh.','БЕРУНИЙСКИЙ РАЙОН','г. Беруни');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735211','QORAO`ZAK TUMANI','Qorao`zak shaharchasi','КАРАУЗЯКСКИЙ РАЙОН','гп Караузяк');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735212','KEGEYLI TUMANI','Kegeyli shaharchasi','КЕГЕЙЛИЙСКИЙ РАЙОН','гп Кегейли');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735215','QO`NG`IROT TUMANI','Qo`ng`irot sh.','КУНГРАДСКИЙ РАЙОН','г. Кунград');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735218','QANLIKO`L TUMANI','Qanliko`l shaharchasi','КАНЛЫКУЛЬСКИЙ РАЙОН','гп Канлыкуль');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735222','MO`YNOQ TUMANI','Mo`ynoq sh.','МУЙНАКСКИЙ РАЙОН','г. Муйнак');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735225','NUKUS TUMANI','Oqmang`it shaharchasi','НУКУССКИЙ РАЙОН','гп Акмангит');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735228','TAXIATOSH TUMANI','Taxiatosh sh.','ТАХИАТАШСКИЙ РАЙОН','г.Тахиаташ');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735230','TAXTAKO`PIR TUMANI','Taxtako`pir shaharchasi','ТАХТАКУПЫРСКИЙ РАЙОН','гп Тахтакупыр');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735233','TO`RTKO`L TUMANI','To`rtko`l sh.','ТУРТКУЛЬСКИЙ РАЙОН','г. Турткуль');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735236','XO`JAYLI TUMANI','Xo`jayli sh.','ХОДЖЕЙЛИЙСКИЙ РАЙОН','г. Ходжейли');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735240','CHIMBOY TUMANI','Chimboy sh.','ЧИМБАЙСКИЙ РАЙОН','г. Чимбай');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735243','SHUMANAY TUMANI','Shumanay sh.','ШУМАНАЙСКИЙ РАЙОН','г. Шуманай');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735250','ELLIKKALA TUMANI','Bo`ston sh.','ЭЛЛИККАЛИНСКИЙ РАЙОН','г. Бустан');
insert into region(soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values ('1735401','Nukus shahri','Город Нукус', null, null);