-- insert regions
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (1, '17', 'O`ZBEKISTON RESPUBLIKASI', 'РЕСПУБЛИКА УЗБЕКИСТАН', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (2, '1703', 'ANDIJON VILOYATI', 'АНДИЖАНСКАЯ ОБЛАСТЬ', 'Andijon sh.', 'г. Андижан');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (3, '1703202', 'OLTINKO`L TUMANI', 'АЛТЫНКУЛЬСКИЙ РАЙОН', 'Oltinko`l a.p.', 'нп Алтынкуль');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (4, '1703203', 'ANDIJON TUMANI', 'АНДИЖАНСКИЙ РАЙОН', 'Kuyganyor shaharchasi', 'гп Куйган - яр');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (5, '1703206', 'BALIQCHI TUMANI', 'БАЛЫКЧИНСКИЙ РАЙОН', 'Baliqchi shaharchasi', 'гп Баликчи');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (6, '1703209', 'BO`Z TUMANI', 'БОЗСКИЙ РАЙОН', 'Bo`z shaharchasi', 'гп Боз');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (7, '1703210', 'BULOQBOSHI TUMANI', 'БУЛАКБАШИНСКИЙ РАЙОН', 'Buloqboshi shaharchasi', 'гп Булокбоши');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (8, '1703211', 'JALAQUDUQ TUMANI', 'ЖАЛАКУДУКСКИЙ РАЙОН', 'Jalaquduq sh.', 'г. Жалакудук');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (9, '1703214', 'IZBOSKAN TUMANI', 'ИЗБАСКАНСКИЙ РАЙОН', 'Paytug sh.', 'г. Пайтуг');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (10, '1703217', 'ULUG`NOR TUMANI', 'УЛУГНОPСКИЙ РАЙОН', 'Oq oltin shaharchasi', 'гп Ок-олтин');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (11, '1703220', 'QO`RG`ONTEPA TUMANI', 'КУРГАНТЕПИНСКИЙ РАЙОН', 'Qo`rg`ontepa sh.', 'г. Кургантепа');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (12, '1703224', 'ASAKA TUMANI', 'АСАКИНСКИЙ РАЙОН', 'Asaka sh.', 'г. Асака');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (13, '1703227', 'MARXAMAT TUMANI', 'МАРХАМАТСКИЙ РАЙОН', 'Marxamat sh.', 'г. Мархамат');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (14, '1703230', 'SHAXRIXON TUMANI', 'ШАХРИХАНСКИЙ РАЙОН', 'Shaxrixon sh.', 'г. Шахрихан');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (15, '1703232', 'PAXTAOBOD TUMANI', 'ПАХТААБАДСКИЙ РАЙОН', 'Paxtaobod sh.', 'г. Пахтаабад');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (16, '1703236', 'XO`JAOBOD TUMANI', 'ХОДЖААБАДСКИЙ РАЙОН', 'Xo`jaobod sh.', 'г. Ходжаабад');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (17, '1703401', 'Andijon shahri', 'Город Андижан', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (18, '1703408', 'Xonobod shahri', 'Город Ханабад', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (19, '1706', 'BUXORO VILOYATI', 'БУХАРСКАЯ ОБЛАСТЬ', 'Buxoro sh.', 'г. Бухара');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (20, '1706204', 'Olot tumani', 'Алатский район', 'Olot sh.', 'г. Алат');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (21, '1706207', 'BUXORO TUMANI', 'БУХАРСКИЙ РАЙОН', 'Gala Osiyo shaharchasi', 'г. Галлаасия');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (22, '1706212', 'VOBKENT TUMANI', 'ВАБКЕНТСКИЙ РАЙОН', 'Vobkent sh.', 'г. Вабкент');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (23, '1706215', 'G`IJDUVON TUMANI', 'ГИЖДУВАНСКИЙ РАЙОН', 'G`ijduvon sh.', 'г. Гиждуван');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (24, '1706219', 'KOGON TUMANI', 'КАГАНСКИЙ РАЙОН', 'Kogon sh.', 'г. Каган');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (25, '1706230', 'QORAKO`L TUMANI', 'КАРАКУЛЬСКИЙ РАЙОН', 'Qorako`l sh.', 'г. Каракуль');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (26, '1706232', 'QOROVULBOZOR TUMANI', 'КАРАУЛБАЗАРСКИЙ РАЙОН', 'Qorovulbozor sh.', 'г. Каpаулбазаp');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (27, '1706240', 'PESHKU TUMANI', 'ПЕШКУНСКИЙ РАЙОН', 'Yangibozor shaharchasi', 'гп Янгибозор');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (28, '1706242', 'ROMITAN TUMANI', 'РОМИТАНСКИЙ РАЙОН', 'Romitan sh.', 'г. Ромитан');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (29, '1706246', 'JONDOR TUMANI', 'ЖОНДОPСКИЙ РАЙОН', 'Jondor shaharchasi', 'гп Жондор');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (30, '1706258', 'SHOFIRKON TUMANI', 'ШАФИРКАНСКИЙ РАЙОН', 'Shofirkon sh.', 'г. Шафиркан');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (31, '1706401', 'Buxoro shahri', 'Город Бухара', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (32, '1706403', 'Kogon shahri', 'Город Каган', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (33,'1708','JIZZAX VILOYATI','Jizzax sh.','ДЖИЗАКСКАЯ ОБЛАСТЬ','г. Джизак');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (34,'1708201','ARNASOY TUMANI','G`oliblar shaharchasi','АРНАСАЙСКИЙ РАЙОН','гп Голиблаp');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (35,'1708204','BAXMAL TUMANI','O`smat shaharchasi','БАХМАЛЬСКИЙ РАЙОН','гп Усмат');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (36,'1708209','G`ALLAOROL TUMANI','G`allaorol sh.','ГАЛЛЯАРАЛЬСКИЙ РАЙОН','г. Галляарал');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (37,'1708212','SHAROF RASHIDOV TUMANI','Uchtepa shaharchasi','ШАРОФ РАШИДОВСКИЙ РАЙОН','гп Уч-тепа');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (38,'1708215','DO`STLIK TUMANI','Do`stlik sh.','ДУСТЛИКСКИЙ РАЙОН','г. Дустлик');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (39,'1708218','ZOMIN TUMANI','Zomin shaharchasi','ЗААМИНСКИЙ РАЙОН','гп Заамин');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (40,'1708220','ZARBDOR TUMANI','Zarbdor shaharchasi','ЗАРБДАРСКИЙ РАЙОН','гп Зарбдар');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (41,'1708223','MIRZACHO`L TUMANI','Gagarin sh.','МИРЗАЧУЛЬСКИЙ РАЙОН','г. Гагарин');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (42,'1708225','ZAFAROBOD TUMANI','Zafarobod shaharchasi','ЗАФАРАБАДСКИЙ РАЙОН','гп Зафарабад');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (43,'1708228','PAXTAKOR TUMANI','Paxtakor sh.','ПАХТАКОРСКИЙ РАЙОН','г. Пахтакор');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (44,'1708235','FORISH TUMANI','Bog`don shaharchasi','ФАРИШСКИЙ РАЙОН','гп Богдон');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (45,'1708237','YANGIOBOD TUMANI','Balandchaqir a.p.','ЯНГИАБАДСКИЙ РАЙОН','нп Баландчакир');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (46,'1708401','Jizzax shahri','Город Джизак', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (47,'1710','QASHQADARYO VILOYATI','Qarshi sh.','КАШКАДАРЬИНСКАЯ ОБЛАСТЬ','г. Карши');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (48,'1710207','G`UZOR TUMANI','G`uzor sh.','ГУЗАРСКИЙ РАЙОН','г. Гузар');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (49,'1710212','DEHQONOBOD TUMANI','Karashina shaharchasi','ДЕХКАНАБАДСКИЙ РАЙОН','гп Корашина');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (50,'1710220','QAMASHI TUMANI','Qamashi sh.','КАМАШИНСКИЙ РАЙОН','г. Камаши');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (51,'1710224','QARSHI TUMANI','Beshkent sh.','КАРШИНСКИЙ РАЙОН','г. Бешкент');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (52,'1710229','KOSON TUMANI','Koson sh.','КАСАНСКИЙ РАЙОН','г. Касан');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (53,'1710232','KITOB TUMANI','Kitob sh.','КИТАБСКИЙ РАЙОН','г. Китаб');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (54,'1710233','MIRISHKOR TUMANI','Yangi Mirishkor shaharchasi','МИРИШКОРСКИЙ РАЙОН','гп Янги Миришкор');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (55,'1710234','MUBORAK TUMANI','Muborak sh.','МУБАРЕКСКИЙ РАЙОН','г. Мубарек');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (56,'1710235','NISHON TUMANI','Yangi Nishon sh.','НИШАНСКИЙ РАЙОН','г. Янги-Нишан');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (57,'1710237','KASBI TUMANI','Mug`lon shaharchasi','КАСБИНСКИЙ РАЙОН','гп Муглон');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (58,'1710242','CHIROQCHI TUMANI','Chiroqchi sh.','ЧИРАКЧИНСКИЙ РАЙОН','г. Чиракчи');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (59,'1710245','SHAHRISABZ TUMANI','Shahrisabz sh.','ШАХРИСАБЗСКИЙ РАЙОН','г. Шахрисабз');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (60,'1710250','YAKKABOG` TUMANI','Yakkabog` sh.','ЯККАБАГСКИЙ РАЙОН','г. Яккабаг');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (61,'1710401','Qarshi','Карши', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (62,'1710405','Shahrisabz','Шахрисабз', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (63,'1712','NAVOIY VILOYATI','Navoiy sh.','НАВОИЙСКАЯ ОБЛАСТЬ','г. Навои');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (64,'1712211','Konimex tumani','Konimex shaharchasi','Канимехский район','гп Канимех');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (65,'1712216','QIZILTEPA TUMANI','Qiziltepa sh.','КЫЗЫЛТЕПИНСКИЙ РАЙОН','г. Кызылтепа');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (66,'1712230','NAVBAHOR TUMANI','Beshrabot a.p.','НАВБАХОРСКИЙ РАЙОН','нп Бешрабад');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (67,'1712234','KARMANA TUMANI','Karmana shaharchasi','КАРМАНИНСКИЙ РАЙОН','гп Кармана');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (68,'1712238','NUROTA TUMANI','Nurota sh.','НУРАТИНСКИЙ РАЙОН','г. Нурата');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (69,'1712244','TOMDI TUMANI','Tomdibuloq shaharchasi','ТАМДЫНСКИЙ РАЙОН','гп Томдибулок');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (70,'1712248','UCHQUDUQ TUMANI','Uchquduq sh.','УЧКУДУКСКИЙ РАЙОН','г. Учкудук');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (71,'1712251','XATIRCHI TUMANI','Yangirabod sh.','ХАТЫРЧИНСКИЙ РАЙОН','г. Янгирабод');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (72,'1712401','Navoiy shahri','Город Навои', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (73,'1712408','Zarafshon','Заpафшан', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (74,'1714','NAMANGAN VILOYATI','Namangan sh.','НАМАНГАНСКАЯ ОБЛАСТЬ','г. Наманган');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (75,'1714204','MINGBULOQ TUMANI','Jo`masho`y shaharchasi','МИНГБУЛАКСКИЙ PАЙОН','гп Джумашуй');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (76,'1714207','KOSONSOY TUMANI','Kosonsoy sh.','КАСАНСАЙСКИЙ РАЙОН','г. Касансай');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (77,'1714212','NAMANGAN TUMANI','Toshbuloq shaharchasi','НАМАНГАНСКИЙ РАЙОН','гп Ташбулак');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (78,'1714216','NORIN TUMANI','Xaqqulobod sh.','НАРЫНСКИЙ РАЙОН','г. Хаккулабад');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (79,'1714219','POP TUMANI','Pop sh.','ПАПСКИЙ РАЙОН','г. Пап');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (80,'1714224','TO`RAQO`RG`ON TUMANI','To`raqo`rg`on sh.','ТУРАКУРГАНСКИЙ РАЙОН','г. Туракурган');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (81,'1714229','UYCHI TUMANI','Uychi shaharchasi','УЙЧИНСКИЙ РАЙОН','гп Уйчи');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (82,'1714234','UCHQO`RG`ON TUMANI','Uchqo`rg`on sh.','УЧКУРГАНСКИЙ РАЙОН','г. Учкурган');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (83,'1714236','CHORTOQ TUMANI','Chortoq sh.','ЧАРТАКСКИЙ РАЙОН','г. Чартак');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (84,'1714237','CHUST TUMANI','Chust sh.','ЧУСТСКИЙ РАЙОН','г. Чуст');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (85,'1714242','YANGIQO`RG`ON TUMANI','Yangiqo`rg`on shaharchasi','ЯНГИКУРГАНСКИЙ РАЙОН','гп Янгикурган');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (86,'1714401','Namangan shahri','Город Наманган', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (87,'1718','SAMARQAND VILOYATI','Samarqand sh.','САМАРКАНДСКАЯ ОБЛАСТЬ','г. Самарканд');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (88,'1718203','Oqdaryo tumani','Loyish shaharchasi','Акдарьинский район','гп Лаиш');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (89,'1718206','BULUNG`UR TUMANI','Bulung`ur sh.','БУЛУНГУРСКИЙ РАЙОН','г. Булунгур');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (90,'1718209','JOMBOY TUMANI','Jomboy sh.','ДЖАМБАЙСКИЙ РАЙОН','г. Джамбай');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (91,'1718212','ISHTIXON TUMANI','Ishtixon sh.','ИШТЫХАНСКИЙ РАЙОН','г. Иштыхан');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (92,'1718215','KATTAQO`RG`ON TUMANI','Payshanba shaharchasi','КАТТАКУРГАНСКИЙ РАЙОН','гп Пайшанба');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (93,'1718216','QO`SHRABOT TUMANI','Qo`shrabot shaharchasi','КОШРАБАДСКИЙ РАЙОН','гп Кушрабад');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (94,'1718218','NARPAY TUMANI','Oqtosh sh.','НАРПАЙСКИЙ РАЙОН','г. Акташ');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (95,'1718224','PAYARIQ TUMANI','Payariq sh.','ПАЙАРЫКСКИЙ РАЙОН','г.Пайаpык');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (96,'1718227','PASTDARG`OM TUMANI','Juma sh.','ПАСТДАРГОМСКИЙ РАЙОН','г. Джума');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (97,'1718230','PAXTACHI TUMANI','Ziyovuddin shaharchasi','ПАХТАЧИЙСКИЙ РАЙОН','гп Зиатдин');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (98,'1718233','SAMARQAND TUMANI','Gulobod shaharchasi','САМАРКАНДСКИЙ РАЙОН','гп Гулабад');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (99,'1718235','NUROBOD TUMANI','Nurobod sh.','НУРАБАДСКИЙ РАЙОН','г. Нурабад');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (100,'1718236','URGUT TUMANI','Urgut sh.','УРГУТСКИЙ РАЙОН','г. Ургут');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (101,'1718238','TAYLOQ TUMANI','Toyloq shaharchasi','ТАЙЛЯКСКИЙ РАЙОН','гп Тайлок');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (102,'1718401','Samarqand shahri','Город Самарканд', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (103,'1718406','Kattaqo`rg`on shahri','Город Каттакурган', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (104,'1722','SURXANDARYO VILOYATI','Termiz sh.','СУРХАНДАРЬИНСКАЯ ОБЛАСТЬ','г. Термез');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (105,'1722201','OLTINSOY TUMANI','Qorliq shaharchasi','АЛТЫНСАЙСКИЙ РАЙОН','гп Корлик');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (106,'1722202','ANGOR TUMANI','Angor shaharchasi','АНГОРСКИЙ РАЙОН','гп Ангор');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (107,'1722204','BOYSUN TUMANI','Boysun sh.','БАЙСУНСКИЙ РАЙОН','г. Байсун');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (108,'1722207','MUZRABOT TUMANI','Xalqobod shaharchasi','МУЗРАБАДСКИЙ РАЙОН','гп Халкабад');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (109,'1722210','DENOV TUMANI','Denov sh.','ДЕНАУСКИЙ РАЙОН','г. Денау');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (110,'1722212','JARQO`RG`ON TUMANI','Jarqo`rg`on sh.','ДЖАРКУРГАНСКИЙ РАЙОН','г. Джаркурган');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (111,'1722214','QUMQO`RG`ON TUMANI','Qumqo`rg`on sh.','КУМКУРГАНСКИЙ РАЙОН','г. Кумкурган');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (112,'1722215','QIZIRIQ TUMANI','Sariq shaharchasi','КИЗИРИКСКИЙ РАЙОН','гп Сарик');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (113,'1722217','SARIOSIYO TUMANI','Sariosiyo shaharchasi','САРИАСИЙСКИЙ РАЙОН','гп Сариасия');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (114,'1722220','TERMIZ TUMANI','Uchqizil shaharchasi','ТЕРМЕЗСКИЙ РАЙОН','гп Учкизил');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (115,'1722221','UZUN TUMANI','Uzun shaharchasi','УЗУНСКИЙ РАЙОН','гп Узун');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (116,'1722223','SHEROBOD TUMANI','Sherobod sh.','ШЕРАБАДСКИЙ РАЙОН','г. Шерабад');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (117,'1722226','SHO`RCHI TUMANI','Sho`rchi sh.','ШУРЧИНСКИЙ РАЙОН','г. Шурчи');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (118,'1722401','Termiz shahri','Город Термез', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (119,'1724','SIRDARYO VILOYATI','Guliston sh.','СЫРДАРЬИНСКАЯ ОБЛАСТЬ','г. Гулистан');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (120,'1724206','OQOLTIN TUMANI','Sardoba shaharchasi','АКАЛТЫНСКИЙ РАЙОН','гп Сардоба');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (121,'1724212','BOYOVUT TUMANI','Boyovut shaharchasi','БАЯУТСКИЙ РАЙОН','гп Баяут');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (122,'1724216','SAYXUNOBOD TUMANI','Sayxun shaharcha','САЙХУНАБАДСКИЙ РАЙОН','гп Сайхун');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (123,'1724220','GULISTON TUMANI','Dehqonobod shaharchasi','ГУЛИСТАНСКИЙ РАЙОН','гп Дехканабад');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (124,'1724226','SARDOBA TUMANI','Paxtaobod shaharchasi','САРДОБСКИЙ РАЙОН','гп Пахтаабад');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (125,'1724228','MIRZAOBOD TUMANI','Navro`z shaharchasi','МИРЗААБАДСКИЙ РАЙОН','гп Навруз');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (126,'1724231','SIRDARYO TUMANI','Sirdaryo sh.','СЫРДАРЬИНСКИЙ РАЙОН','г. Сырдарья');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (127,'1724235','XOVOS TUMANI','Xovos shaharchasi','ХАВАССКИЙ РАЙОН','гп Хавас');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (128,'1724401','Guliston shahri','Город Гулистан', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (129,'1724410','Shirin shahri','Город Шиpин', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (130,'1724413','Yangiyer shahri','Город Янгиеp', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (131,'1726','TOSHKENT SHAHRI','ГОРОД ТАШКЕНТ', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (132,'1726262','Uchtepa tumani','Учтепинский район', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (133,'1726264','Bektemir tumani','Бектемирский район', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (134,'1726266','Yunusobod tumani','Юнусабадский район', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (135,'1726269','Mirzo Ulug`bek tumani','Мирзо-Улугбекский район', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (136,'1726273','Mirobod tumani','Мирабадский район', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (137,'1726277','Shayxontoxur tumani','Шайхантахурский район', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (138,'1726280','Olmazor tumani','Алмазарский район', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (139,'1726283','Sirg`ali tumani','Сергелийский район', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (140,'1726287','Yakkasaroy tumani','Яккасарайский район', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (141,'1726290','Yashnobod tumani','Яшнободский район', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (142,'1726294','Chilonzor tumani','Чиланзарский район', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (143,'1727','TOSHKENT VILOYATI','Toshkent sh.','ТАШКЕНТСКАЯ ОБЛАСТЬ','г. Ташкент');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (144,'1727206','OQQO`RG`ON TUMANI','Oqqo`rg`on sh.','АККУРГАНСКИЙ РАЙОН','г. Аккурган');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (145,'1727212','OHANGARON TUMANI','Ohangaron sh.','АХАНГАРАНСКИЙ РАЙОН','г. Ахангаран');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (146,'1727220','BEKOBOD TUMANI','Zafar shaharchasi','БЕКАБАДСКИЙ РАЙОН','гп Зафар');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (147,'1727224','BO`STONLIQ TUMANI','G`azalkent sh.','БОСТАНЛЫКСКИЙ РАЙОН','г. Газалкент');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (148,'1727228','BO`KA TUMANI','Bo`ka sh.','БУКИНСКИЙ РАЙОН','г. Бука');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (149,'1727233','QIYICHIRCHIQ TUMANI','Do`stobod sh.','КУЙИЧИРЧИКСКИЙ РАЙОН','г. Дустобод');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (150,'1727237','ZANGIOTA TUMANI','Eshonguzar shaharchasi','ЗАНГИАТИНСКИЙ РАЙОН','гп Эшангузар');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (151,'1727239','YUQORICHIRCHIQ TUMANI','Yangibozor shaharchasi','ЮКОРИЧИРЧИКСКИЙ РАЙОН','гп Янгибазар');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (152,'1727248','QIBRAY TUMANI','Qibray shaharchasi','КИБРАЙСКИЙ РАЙОН','гп Кибрай');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (153,'1727249','PARKENT TUMANI','Parkent sh.','ПАРКЕНТСКИЙ РАЙОН','г. Паркент');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (154,'1727250','PSKENT TUMANI','Pskent sh.','ПСКЕНТСКИЙ РАЙОН','г. Пскент');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (155,'1727253','O`RTACHIRCHIQ TUMANI','To`ytepa sh.','УРТАЧИРЧИКСКИЙ РАЙОН','г. Тойтепа');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (156,'1727256','CHINOZ TUMANI','Chinoz sh.','ЧИНАЗСКИЙ РАЙОН','г. Чиназ');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (157,'1727259','YANGIYO`L TUMANI','Yangiyo`l sh.','ЯНГИЮЛЬСКИЙ РАЙОН','г.Янгиюль');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (158,'1727265','TOSHKENT TUMANI','Keles sh.','ТАШКЕНТСКИЙ РАЙОН','г.Келес');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (159,'1727404','Olmaliq shahri','Город Алмалык', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (160,'1727407','Angren shahri','Город Ангрен', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (161,'1727413','Bekobod shahri','Город Бекабад', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (162,'1727419','Chirchiq shahri','Город Чиpчик', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (163,'1730','FARG`ONA VILOYATI','Farg`ona sh.','ФЕРГАНСКАЯ ОБЛАСТЬ','г. Фергана');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (164,'1730203','OLTIARIQ TUMANI','Oltiariq shaharchasi','АЛТЫАРЫКСКИЙ РАЙОН','гп Алтыарык');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (165,'1730206','QO`SHTEPA TUMANI','Langar a.p.','КУШТЕПИНСКИЙ РАЙОН','нп Лангар');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (166,'1730209','BOG`DOD TUMANI','Bog`dod shaharchasi','БАГДАДСКИЙ РАЙОН','гп Багдад');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (167,'1730212','BUVAYDA TUMANI','Ibrat shaharchasi','БУВАЙДИНСКИЙ РАЙОН','гп Ибрат');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (168,'1730215','BESHARIQ TUMANI','Beshariq sh.','БЕШАРЫКСКИЙ РАЙОН','г. Бешарык');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (169,'1730218','QUVA TUMANI','Quva sh.','КУВИНСКИЙ РАЙОН','г. Кува');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (170,'1730221','UCHKO`PRIK TUMANI','Uchko`prik shaharchasi','УЧКУПРИКСКИЙ РАЙОН','гп Учкуприк');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (171,'1730224','RISHTON TUMANI','Rishton sh.','РИШТАНСКИЙ РАЙОН','г. Риштан');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (172,'1730226','SO`X TUMANI','Ravon shaharchasi','СОХСКИЙ РАЙОН','гп Равон');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (173,'1730227','TOSHLOQ TUMANI','Toshloq shaharchasi','ТАШЛАКСКИЙ РАЙОН','гп Ташлак');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (174,'1730230','O`ZBEKISTON TUMANI','Yaypan sh.','УЗБЕКИСТАНСКИЙ РАЙОН','г. Яйпан');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (175,'1730233','FARG`ONA TUMANI','Chimyon shaharchasi','ФЕРГАНСКИЙ РАЙОН','гп Чимен');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (176,'1730236','DANG`ARA TUMANI','Dang`ara shaharchasi','ДАНГАРИНСКИЙ РАЙОН','гп Дангара');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (177,'1730238','FURQAT TUMANI','Navbahor shaharchasi','ФУРКАТСКИЙ РАЙОН','гп Навбахор');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (178,'1730242','YOZYOVON TUMANI','Yozyovon shaharchasi','ЯЗЪЯВАНСКИЙ РАЙОН','гп Язъяван');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (179,'1730401','Farg`ona shahri','Город Фергана', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (180,'1730405','Qo`qon shahri','Город Коканд', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (181,'1730408','Quvasoy shahri','Город Кувасай', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (182,'1730412','Marg`ilon shahri','Город Маpгилан', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (183,'1733','XORAZM VILOYATI','Urganch sh.','ХОРЕЗМСКАЯ ОБЛАСТЬ','г. Ургенч');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (184,'1733204','BOG`OT TUMANI','Bog`ot shaharchasi','БАГАТСКИЙ РАЙОН','гп Багат');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (185,'1733208','GURLAN TUMANI','Gurlan shaharchasi','ГУРЛЕНСКИЙ РАЙОН','гп Гурлен');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (186,'1733212','QO`SHKO`PIR TUMANI','Qo`shko`pir shaharchasi','КОШКУПЫРСКИЙ РАЙОН','гп Кошкупыр');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (187,'1733217','URGANCH TUMANI','Qoroul a.p.','УРГЕНЧСКИЙ РАЙОН','нп Караул');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (188,'1733220','XAZORASP TUMANI','Xazorasp shaharchasi','ХАЗАРАСПСКИЙ РАЙОН','гп Хазарасп');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (189,'1733223','XONQA TUMANI','Xonqa shaharchasi','ХАНКИНСКИЙ РАЙОН','гп Ханка');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (190,'1733226','XIVA TUMANI','Xiva sh.','ХИВИНСКИЙ РАЙОН','г. Хива');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (191,'1733230','SHOVOT TUMANI','Shovot shaharchasi','ШАВАТСКИЙ РАЙОН','гп Шават');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (192,'1733233','YANGIARIQ TUMANI','Yangiariq shaharchasi','ЯНГИАРЫКСКИЙ РАЙОН','гп Янгиарык');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (193,'1733236','YANGIBOZOR TUMANI','Yangibozor shaharchasi','ЯНГИБАЗАРСКИЙ РАЙОН','гп Янгибазар');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (194,'1733401','Urganch shahri','Город Ургенч', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (195,'1733406','Xiva shahri','Город Хива', null, null);
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (196,'1735','Qoraqalpog`iston Respublikasi','Nukus sh.','Республика Каракалпакстан','г. Hукус');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (197,'1735204','AMUDARYO TUMANI','Mang`it sh.','АМУДАРЬИНСКИЙ РАЙОН','г. Мангит');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (198,'1735207','BERUNIY TUMANI','Beruniy sh.','БЕРУНИЙСКИЙ РАЙОН','г. Беруни');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (199,'1735211','QORAO`ZAK TUMANI','Qorao`zak shaharchasi','КАРАУЗЯКСКИЙ РАЙОН','гп Караузяк');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (200,'1735212','KEGEYLI TUMANI','Kegeyli shaharchasi','КЕГЕЙЛИЙСКИЙ РАЙОН','гп Кегейли');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (201,'1735215','QO`NG`IROT TUMANI','Qo`ng`irot sh.','КУНГРАДСКИЙ РАЙОН','г. Кунград');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (202,'1735218','QANLIKO`L TUMANI','Qanliko`l shaharchasi','КАНЛЫКУЛЬСКИЙ РАЙОН','гп Канлыкуль');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (203,'1735222','MO`YNOQ TUMANI','Mo`ynoq sh.','МУЙНАКСКИЙ РАЙОН','г. Муйнак');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (204,'1735225','NUKUS TUMANI','Oqmang`it shaharchasi','НУКУССКИЙ РАЙОН','гп Акмангит');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (205,'1735228','TAXIATOSH TUMANI','Taxiatosh sh.','ТАХИАТАШСКИЙ РАЙОН','г.Тахиаташ');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (206,'1735230','TAXTAKO`PIR TUMANI','Taxtako`pir shaharchasi','ТАХТАКУПЫРСКИЙ РАЙОН','гп Тахтакупыр');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (207,'1735233','TO`RTKO`L TUMANI','To`rtko`l sh.','ТУРТКУЛЬСКИЙ РАЙОН','г. Турткуль');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (208,'1735236','XO`JAYLI TUMANI','Xo`jayli sh.','ХОДЖЕЙЛИЙСКИЙ РАЙОН','г. Ходжейли');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (209,'1735240','CHIMBOY TUMANI','Chimboy sh.','ЧИМБАЙСКИЙ РАЙОН','г. Чимбай');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (210,'1735243','SHUMANAY TUMANI','Shumanay sh.','ШУМАНАЙСКИЙ РАЙОН','г. Шуманай');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (211,'1735250','ELLIKKALA TUMANI','Bo`ston sh.','ЭЛЛИККАЛИНСКИЙ РАЙОН','г. Бустан');
insert into region(id, soato, name_uz_uz, name_ru_ru, center_region_name_uz_uz, center_region_name_ru_ru) values (212,'1735401','Nukus shahri','Город Нукус', null, null);